baselines/README.md

Turbot Terraform Provider links point to dead links, updated to the v5 docs page.

Update Terraform Provider Links

---

baselines/aws/aws_account_import/default.tfvars
baselines/aws/aws_account_import/main.tf
baselines/aws/aws_account_import/variables.tf

It is now require that an account has the following metadata in order for the IAM mod to run correctly.
```json
"aws" : {
"accountId" : "1234567890",
"partition" : "aws"
}
```
Modify the script to include this

Fix aws account import script to work with new account structure

---

api_examples/graphql/queries/resource_control_policy.graphql

Initial commit of a query that lists each AWS resource, then the controls and policies associated with that resource.
closes #58

GraphQL Query - List AWS resource and associated policies and controls #58

---

control_objectives/aws_rds_db_approved/README.md
control_objectives/aws_rds_db_approved/default.tfvars
control_objectives/aws_rds_db_approved/main.tf
control_objectives/aws_rds_db_approved/variables.tf

AWS RDS control objective to check RDS approval based on instance/ engine type
closes #60

Control Objective - Set approved instance and engine types #60

---

baselines/azure/azure_sub_import/default.tfvars

Changed spelling of clound_environment to cloud_environment.
closes #63

Base Line - Fixed spelling in Azure default.tfvars file #64

---

control_objectives/aws_ec2_enforce_encryption/README.md
control_objectives/aws_ec2_enforce_encryption/default.tfvars
control_objectives/aws_ec2_enforce_encryption/main.tf
control_objectives/aws_ec2_enforce_encryption/variables.tf

Control objective to create two policies that check for approval on snapshots and volumes, and then also creates two policies that alarm the approved control if encryption is not set at `AWS managed key or higher`.
closes #73

Control Objective - EC2 enforcement of encryption on volumes and snapshots #73

---

control_objectives/aws_iam_turbot_service_roles/README.md
control_objectives/aws_iam_turbot_service_roles/default.tfvars
control_objectives/aws_iam_turbot_service_roles/main.tf
control_objectives/aws_iam_turbot_service_roles/variables.tf

Provides a Terraform configuration for creating a smart folder and creating one policy to check the existence of Turbot service roles in an AWS account, and three subsequent policies that define which roles to check.
closes #111

Control Objective - Turbot Service Roles #111

---

control_objectives/turbot_iam_roles/README.md
control_objectives/turbot_iam_roles/default.tfvars
control_objectives/turbot_iam_roles/main.tf
control_objectives/turbot_iam_roles/variables.tf

Provides a Terraform configuration for creating a smart folder and sets a policy to enable Turbot creating AWS IAM roles. Two policies are also created to check for AWS boundary policies.
closes #113

Control Objective - Turbot IAM Roles #113

---

control_objectives/aws_vpc_restrict_nat/README.md
control_objectives/aws_vpc_restrict_nat/default.tfvars
control_objectives/aws_vpc_restrict_nat/main.tf
control_objectives/aws_vpc_restrict_nat/variables.tf

Provides a Terraform configuration for creating a smart folder and applying example turbot policy settings to restrict NAT Gateway usage. 
closes #115

Control Objective - Restrict NAT Gateway within VPC #115

---

control_objectives/aws_s3_limit_public_access/README.md
control_objectives/aws_s3_limit_public_access/default.tfvars
control_objectives/aws_s3_limit_public_access/main.tf
control_objectives/aws_s3_limit_public_access/variables.tf

Provides a Terraform configuration for creating a smart folder and applying example turbot policy settings for an S3 bucket. One set of policies apply checks for public access settings on the bucket itself, while the other set checks for public access settings at the account level in AWS.
closes #117

Control Objective - S3 limit public access #117

---

calculated_policies/aws_ec2_public_subnet/README.md
calculated_policies/aws_ec2_public_subnet/default.tfvars
calculated_policies/aws_ec2_public_subnet/main.tf
calculated_policies/aws_ec2_public_subnet/variables.tf

New calculated policy that alarms if an EC2 instance is in a subnet that has an associated route table, and that route table contains a route to an IGW.
closes #129

Calculated Policy - Alarm if EC2 instance is in public subnet #129

---

control_objectives/aws_vpc_security_group_rules/README.md
control_objectives/aws_vpc_security_group_rules/default.tfvars
control_objectives/aws_vpc_security_group_rules/main.tf
control_objectives/aws_vpc_security_group_rules/variables.tf

closes #166
REJECTING 22, 3389 ingress from public internet 0.0.0.0/0 and ipv6 ::/0
APPROVING rds default ports of 1433, 1521, 3306, 5432 from 10.0.0.0/8 are allowed
APPROVING 80 and 443 are allowed egress to 0.0.0.0/0 but nothing else
Also AWS CIS v1.2 Section 4.01 Ensure no security groups allow ingress from 0.0.0.0/0 to port 22 (Scored) and # 4.02 Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389 (Scored)
>Keep in mind that the security group rule policies are examples only! They must be modified to match organizational requirements.

Control Objective - AWS VPC Security Group Rules check #166

---

baselines/aws/aws_setup/main.tf

In the baseline, we referenced the incorrect Turbot policy in the comment. This has been fixed.
closes #267

 Baseline - Fix incorrect policy reference #267 

---

baselines/getting_started/aws/aws_check_cost_controls/README.md
baselines/getting_started/aws/aws_check_cost_controls/variables.tf
baselines/getting_started/aws/aws_check_encryption/README.md
baselines/getting_started/aws/aws_check_encryption/variables.tf
baselines/getting_started/aws/aws_check_public_access/README.md
baselines/getting_started/aws/aws_check_public_access/variable.tf
baselines/getting_started/aws/aws_check_regions/README.md
baselines/getting_started/aws/aws_check_regions/variables.tf
baselines/getting_started/aws/aws_check_stack/aws_account_iam_stack_policies.tf
baselines/getting_started/aws/aws_check_stack/outputs.tf
baselines/getting_started/aws/aws_check_stack/variables.tf

Clean AWS baseline TF files to remove default and readme updates. Closes #441

---

baselines/getting_started/gcp/gcp_baseline/README.md
baselines/getting_started/gcp/gcp_baseline/variables.tf

Baseline - Clean GCP baseline TF files to remove default and readme updates #443

---

api_examples/graphql/queries/list_control_counts_by_cloud_account.graphql

Adds a graphql query to get a list of cloud accounts then the number of active and total controls for each account.

Control counts cloud account

---

api_examples/graphql/queries/gcp_project_import.graphql

There's a missing comma in the variables section.

Missing Comma in Variables

---

policy_packs/gcp/computeengine/enforce_instances_to_not_use_unapproved_images/README.md
policy_packs/gcp/computeengine/enforce_instances_to_not_use_unapproved_images/main.tf
policy_packs/gcp/computeengine/enforce_instances_to_not_use_unapproved_images/policies.tf
policy_packs/gcp/computeengine/enforce_instances_to_not_use_unapproved_images/providers.tf

Add GCP Compute Engine Policy pack

---

policy_packs/aws/vpc/enforce_default_security_groups_to_not_exist/README.md
policy_packs/aws/vpc/enforce_default_security_groups_to_not_exist/main.tf
policy_packs/aws/vpc/enforce_default_security_groups_to_not_exist/policies.tf
policy_packs/aws/vpc/enforce_default_security_groups_to_not_exist/providers.tf

Add AWS VPC Policy Pack 5

---

policy_packs/aws/backup/enforce_ebs_volume_backups/README.md
policy_packs/aws/backup/enforce_ebs_volume_backups/main.tf
policy_packs/aws/backup/enforce_ebs_volume_backups/policies.tf
policy_packs/aws/backup/enforce_ebs_volume_backups/providers.tf

- Creates the required IAM role.
- Creates the backup vault, backup selection and backup plan.
- README describes how to roll out and decommission.

Policy Pack for backing up EBS volumes using AWS Backup.

---

.github/workflows/baselines.yml

The primary goal is to ensure that any changes made to the guardrails-samples/baselines folder are automatically applied to our designated workspace for validation purposes:
**Real-time Validation**: By automatically applying changes to the Turbot workspace, we can continuously validate the correctness of our baselines and catch any potential issues early in the development process.
**Streamlined Workflow**: This setup eliminates the need for manual application of changes, reducing the risk of human error and speeding up the development workflow.

Add GitHub Action for Baselines

---

enterprise_installation/guardrails_security_groups.yml

- Useful for enterprise customers who are using custom VPCs.
- This CFN serves as a convenient starting point for what ports are required and the Guardrails security group naming conventions.

Restore Guardails Default Security Groups

---

guardrails_utilities/python_utils/delete_resources_batches/README.md
guardrails_utilities/python_utils/delete_resources_batches/delete_resources_batches.py
guardrails_utilities/python_utils/delete_resources_batches/requirements.txt

```
$ python3 delete_resources_batches.py --profile punisher  --resource-id  342438312747854   --disable --execute
Testing connection to https://punisher-turbot.cloud.turbot-dev.com ...
Success! Status Code: 200
Disabling discovery policies for resource ID: 342438312747854...
Found 9 policies to update.
Updating policy tmod:@turbot/azure-activedirectory#/policy/types/customDomainCmdb to 'Skip'...
Updating policy tmod:@turbot/azure-activedirectory#/policy/types/clientSecretCmdb to 'Skip'...
Updating policy tmod:@turbot/azure-activedirectory#/policy/types/servicePrincipalCmdb to 'Skip'...
Updating policy tmod:@turbot/azure-activedirectory#/policy/types/applicationCmdb to 'Skip'...
Updating policy tmod:@turbot/azure-activedirectory#/policy/types/groupCmdb to 'Skip'...
Updating policy …
```

Add delete_resources_batches script

---

baselines/guardrails/turbot_profiles/main.tf

Update Baselines for turbot.com directory profile Id to use: "turbot.{{profile.$source.name}}"

Update Baselines for turbot.com directory profile Id
