- api_examples/graphql/clients/python/azure_import.py
- api_examples/graphql/queries/azure_sub_import.graphql
Python script example and base graphql query for importing Azure subscriptions.
> Include the Azure import script and graphql query

- api_examples/graphql/clients/python/azure_import.py
- api_examples/graphql/queries/azure_sub_import.graphql
Python example for importing an Azure subscription.
> Addition of the Azure Import script

- baselines/turbot/mod_install/main.tf
Updated the count for the aws-vpc-* mods with respective values.
> updated count= <values> for aws-vpc-* mods

- baselines/aws/aws_account_import/default.tfvars
- baselines/aws/aws_account_import/main.tf
- baselines/aws/aws_account_import/variables.tf
> Allow account input script to use user specified AWS profiles

- api_examples/graphql/clients/node/calculate-policy-values-for-filter/package-lock.json
- api_examples/graphql/clients/node/calculate-policy-values-for-filter/package.json
- api_examples/graphql/clients/node/controls-in-alert-by-tag/package-lock.json
- api_examples/graphql/clients/node/controls-in-alert-by-tag/package.json
- api_examples/graphql/clients/node/list-all-policies-in-environment/package-lock.json
- api_examples/graphql/clients/node/list-all-policies-in-environment/package.json
- api_examples/graphql/clients/node/list-mods-to-updated/package-lock.json
- api_examples/graphql/clients/node/list-mods-to-updated/package.json
- api_examples/graphql/clients/node/run-controls-for-filter/package-lock.json
- api_examples/graphql/clients/node/run-controls-for-filter/package.json
- api_examples/graphql/clients/node/set-api-enabled-policies-for-gcp-services/package-lock.json
- api_examples/graphql/clients/node/set-api-enabled-policies-for-gcp-services/package.json
- api_examples/graphql/clients/node/set-api-enabled-policy-for-gcp/package-lock.json
- api_examples/graphql/clients/node/set-api-enabled-policy-for-gcp/package.json
- api_examples/graphql/clients/node/set-enabled-policies-for-gcp-services/package-lock.json
- api_examples/graphql/clients/node/set-enabled-policies-for-gcp-services/package.json
- api_examples/graphql/clients/node/set-policy-to-enable-gcp-service/package-lock.json
- api_examples/graphql/clients/node/set-policy-to-enable-gcp-service/package.json
- api_examples/graphql/clients/node/simple-query/package-lock.json
- api_examples/graphql/clients/node/simple-query/package.json
> Fix node package names

- api_examples/graphql/queries/controls-to-investigate.graphql
> Add example for unhealthy controls #44

- control_objectives/aws_vpc_flow_logs/README.md
- control_objectives/aws_vpc_flow_logs/default.tfvars
- control_objectives/aws_vpc_flow_logs/main.tf
- control_objectives/aws_vpc_flow_logs/variables.tf
> Control Objective - Flow log configuration check #50

- control_objectives/aws_vpc_delete_default/README.md
- control_objectives/aws_vpc_delete_default/default.tfvars
- control_objectives/aws_vpc_delete_default/main.tf
- control_objectives/aws_vpc_delete_default/variables.tf
Terraform plan to create a smart folder with policies that check if a default vpc exists within a vpc.
closes #51
> Control Objective - Check if default VPC exists #51

- control_objectives/aws_rds_encryption_at_rest/README.md
- control_objectives/aws_rds_encryption_at_rest/default.tfvars
- control_objectives/aws_rds_encryption_at_rest/main.tf
- control_objectives/aws_rds_encryption_at_rest/variables.tf
> Control Objective- Set DB instance encryption at rest policy #53

- baselines/azure/azure_sub_import/main.tf
- baselines/azure/azure_sub_import_ro/main.tf
> Base Lines - Fix Azure to work with Subscription Import #48

- control_objectives/aws_audit_logging/README.md
- control_objectives/aws_audit_logging/default.tfvars
- control_objectives/aws_audit_logging/main.tf
- control_objectives/aws_audit_logging/variables.tf
> Control Objective - Enable Global CloudTrail #52

- control_objectives/aws_iam_cross_account/README.md
- control_objectives/aws_iam_cross_account/default.tfvars
- control_objectives/aws_iam_cross_account/main.tf
- control_objectives/aws_iam_cross_account/variables.tf
> Control Objectives - Set trusted accounts and enable trust policy #59

- installation/workspace-template.yml
Also intializing the installation folder. we can add any necessary files for turbot enterprise install here
closes #61
> Installation - Create a workspace #61

- baselines/gcp/gcp_project_import/README.md
- baselines/gcp/gcp_project_import/default.tfvars
- baselines/gcp/gcp_project_import/main.tf
- baselines/gcp/gcp_project_import/variables.tf
Added scripts to import the GCP projects on turbot.
closes #69
> Base Line - Common configuration for importing GCP Projects #69

- api_examples/graphql/queries/controls-to-investigate.graphql
- api_examples/graphql/queries/install_mod.graphql
- api_examples/graphql/queries/list_control_summaries_by_control_category.graphql
- api_examples/graphql/queries/list_controls.graphql
- api_examples/graphql/queries/list_controls_by_resource_type.graphql
- api_examples/graphql/queries/list_controls_by_tags.graphql
- api_examples/graphql/queries/list_controls_in_specific_account.graphql
- api_examples/graphql/queries/list_controls_ten_oldest_alerts.graphql
- api_examples/graphql/queries/list_controls_ten_oldest_alerts_for_s3.graphql
- api_examples/graphql/queries/list_installed_mods_by_resource_type.graphql
- api_examples/graphql/queries/list_resourcelist_by_resource_type_in_specific_account.graphql
- api_examples/graphql/queries/list_resources_by_resource_type.graphql
- api_examples/graphql/queries/list_resources_by_resource_type_with_specific_tag.graphql
- api_examples/graphql/queries/list_resources_by_resource_type_with_write_acl.graphql
- api_examples/graphql/queries/storage-resources.graphql
- api_examples/graphql/queries/turbot-metadata.graphql
> Add update policy example #23

- control_objectives/aws_s3_encryption/README.md
- control_objectives/aws_s3_encryption/default.tfvars
- control_objectives/aws_s3_encryption/main.tf
- control_objectives/aws_s3_encryption/variables.tf
Control objective that creates a smart folder and sets an object encryption in transit policy as well as enforcing encryption at rest in an S3 bucket.
> Control Objective - S3 encryption at rest and object in transit #72

- baselines/gcp/gcp_services/default.tfvars
closes #95
Services include:
- Composer
- Scheduler
> Add new GCP services to gcp_services baseline #95

- control_objectives/aws_rds_audit_logging/README.md
- control_objectives/aws_rds_audit_logging/default.tfvars
- control_objectives/aws_rds_audit_logging/main.tf
- control_objectives/aws_rds_audit_logging/variables.tf
Provides a Terraform configuration for creating a smart folder and applying example Turbot policy settings checking for Audit Logging DB Parameters on RDS instances.
> Control Objective - RDS Audit Logging #112

- control_objectives/turbot_logging_buckets/README.md
- control_objectives/turbot_logging_buckets/default.tfvars
- control_objectives/turbot_logging_buckets/main.tf
- control_objectives/turbot_logging_buckets/variables.tf
Provides a Terraform configuration for creating a smart folder and setting policies to check for Turbot logging bucket existence as well as enforcing versioning, encryption, and regional approval policies.
> Control Objective - Turbot Logging Buckets #114

- installation/workspace-template.yml
Update the workspace manager to match the site
> Installation - Updating workspace manager template #116

- api_examples/graphql/queries/gcp_project_import.graphql
> GraphQL - Mutation to import GCP Project #120

- baselines/README.md
Removed:
Mod Install
AWS S3 Baseline
AWS CIS Remediation
Fixed:
Azure Subscription ReadOnly mode
> Remove & Fix Broken Links #128

- stack_examples/aws_ssm_package_installer/README.md
- stack_examples/aws_ssm_package_installer/default.tfvars
- stack_examples/aws_ssm_package_installer/main.tf
- stack_examples/aws_ssm_package_installer/variables.tf
Create a SSM document for instance package installation.
closes #125
> Create a SSM document for instance package installation #125

- repo-tools/templates/calc-policy-template.njk
> Repo Tools - Add safe string mode to rendering #156

- calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/default.tfvars
- calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/variables.tf
- calculated_policies/aws_sqs_approved/README.md
- calculated_policies/aws_sqs_approved/default.tfvars
- calculated_policies/aws_sqs_approved/main.tf
- calculated_policies/aws_sqs_approved/variables.tf
- repo-tools/templates/calc-policy-template.njk
- repo-tools/templates/calc-policy/aws_sqs_approved/template.yml
> Calculated Policies - aws_sqs_approved returning incorrect value for not approved case #155

- calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/README.md
- calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/default.tfvars
- calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/main.tf
- calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/variables.tf
- repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_approved_account_ami/template.yml
> Calculated Policy - Instance Approved if published by Approved Account #162

- calculated_policies/aws_ec2_instance_approved_usage_local_ami/README.md
- calculated_policies/aws_ec2_instance_approved_usage_local_ami/default.tfvars
- calculated_policies/aws_ec2_instance_approved_usage_local_ami/main.tf
- calculated_policies/aws_ec2_instance_approved_usage_local_ami/variables.tf
- repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_local_ami/template.yml
> Create a Calculated Policy to set Instance Approved if using Local AMI #153

- calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/README.md
- calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/default.tfvars
- calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/main.tf
- calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/variables.tf
- repo-tools/templates/calc-policy/aws_ec2_instance_approved_usage_trusted_ami/template.yml
> Calculated Policy - Instance Approved if using Trusted AMI #158

- control_objectives/aws_iam_credential_report/README.md
- control_objectives/aws_iam_credential_report/default.tfvars
- control_objectives/aws_iam_credential_report/main.tf
- control_objectives/aws_iam_credential_report/variables.tf
> Control Objective - Enable IAM credential report policy #167

- control_objectives/aws_rds_public_access/README.md
- control_objectives/aws_rds_public_access/default.tfvars
- control_objectives/aws_rds_public_access/main.tf
- control_objectives/aws_rds_public_access/variables.tf
> Control Objective - RDS Public Access Check #169

- control_objectives/aws_iam_password_settings/README.md
- control_objectives/aws_iam_password_settings/default.tfvars
- control_objectives/aws_iam_password_settings/main.tf
- control_objectives/aws_iam_password_settings/variables.tf
> Control Objective - AWS IAM Account Password Settings #170

- control_objectives/aws_vpc_restrict_igw/README.md
- control_objectives/aws_vpc_restrict_igw/default.tfvars
- control_objectives/aws_vpc_restrict_igw/main.tf
- control_objectives/aws_vpc_restrict_igw/variables.tf
> Control Objective - Restrict IGW #171

- control_objectives/turbot_aws_event_handlers/README.md
- control_objectives/turbot_aws_event_handlers/default.tfvars
- control_objectives/turbot_aws_event_handlers/main.tf
- control_objectives/turbot_aws_event_handlers/variables.tf
> Control Objective - Turbot AWS Event Handlers #172

- control_objectives/aws_rds_storage_space_alarms/README.md
- control_objectives/aws_rds_storage_space_alarms/default.tfvars
- control_objectives/aws_rds_storage_space_alarms/main.tf
- control_objectives/aws_rds_storage_space_alarms/variables.tf
> Control Objective - RDS Storage Space Alarms #173

- control_objectives/aws_ec2_instance_approved/main.tf
> Control Objectives - Smart folder missing for calculated policy #174

- calculated_policies/aws_ec2_instance_age/README.md
- calculated_policies/aws_ec2_public_subnet/README.md
- calculated_policies/aws_lambda_in_vpc/README.md
- calculated_policies/aws_s3_bucket_tagging_template/README.md
- calculated_policies/aws_sqs_approved/README.md
- calculated_policies/azure_load_balancer_prohibited_ports/README.md
- calculated_policies/multi_cloud_storage_cost_savings/README.md
closes #175
Edited all the links in the calc policies in TDK to refer to our documentation for Terraform rather than the old github repo.
> Calculated Policies - Fixed Turbot Terraform Provider weblink #175

- calculated_policies/aws_guardduty_detector_approved_usage/README.md
- calculated_policies/aws_guardduty_detector_approved_usage/default.tfvars
- calculated_policies/aws_guardduty_detector_approved_usage/main.tf
- calculated_policies/aws_guardduty_detector_approved_usage/variables.tf
- repo-tools/templates/calc-policy/aws_guardduty_detector_approved_usage/template.yml
> Calculated Policy - Restrict GuardDuty Detector master account #144

- calculated_policies/aws_lambda_not_approved_cross_account_access/README.md
- calculated_policies/aws_lambda_not_approved_cross_account_access/default.tfvars
- calculated_policies/aws_lambda_not_approved_cross_account_access/main.tf
- calculated_policies/aws_lambda_not_approved_cross_account_access/variables.tf
- repo-tools/templates/calc-policy/aws_lambda_not_approved_cross_account_access/template.yml
> Calculated Policy - Restrict Lambda Cross Account Access #132

- calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/README.md
- calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/default.tfvars
- calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/main.tf
- calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/variables.tf
- repo-tools/templates/calc-policy/aws_rds_db_cluster_snapshot_cross_account_access/template.yml
> Calculated Policy - AWS > RDS > DB Cluster Snapshot [Manual] Cross Account Access #181

- calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/README.md
- calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/default.tfvars
- calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/main.tf
- calculated_policies/aws_s3_bucket_approved_usage_name_dns_compliant/variables.tf
- repo-tools/templates/calc-policy/aws_s3_bucket_approved_usage_name_dns_compliant/template.yml
> Calculated Policy - AWS > S3 > Bucket name DNS compliant #177

- calculated_policies/aws_lambda_in_vpc/main.tf
- calculated_policies/aws_rds_db_cluster_snapshot_cross_account_access/main.tf
- calculated_policies/aws_redshift_restrict_cross_account_snapshot_access/main.tf
- calculated_policies/aws_s3_approved_static_website_hosting_requires_cloud_front/main.tf
- calculated_policies/aws_sqs_approved/main.tf
> Calculated Policy - Bring in Check:Approved to missing examples #186

- baselines/README.md
- calculated_policies/README.md
- repo-tools/templates/calc-policy/index-document.njk
>  Documentation - Give steps to run calculated policy in index file #199

- baselines/azure/azure_eventing/default.tfvars
- baselines/azure/azure_eventing/main.tf
- baselines/azure/azure_eventing/variables.tf
> Base Lines - Expand Azure eventing to allow for event type choices #103

- baselines/README.md
- calculated_policies/README.md
- repo-tools/templates/calc-policy/index-document.njk
> Documentation - Calculated Policy link updates #207

- calculated_policies/README.md
- calculated_policies/azure_storage_container_approved_usage_not_public/README.md
- calculated_policies/azure_storage_container_approved_usage_not_public/default.tfvars
- calculated_policies/azure_storage_container_approved_usage_not_public/main.tf
- calculated_policies/azure_storage_container_approved_usage_not_public/variables.tf
- repo-tools/templates/calc-policy/azure_storage_container_approved_usage_not_public/template.yml
> Calculated Policy - Azure > Storage > Container approved if access level is not public #203

- .vscode/settings.json
- calculated_policies/README.md
- calculated_policies/aws_ec2_instance_age/README.md
- calculated_policies/aws_ec2_instance_approved_usage_approved_account_ami/README.md
- calculated_policies/aws_ec2_instance_approved_usage_local_ami/README.md
- calculated_policies/aws_ec2_instance_approved_usage_trusted_ami/README.md
- calculated_policies/aws_ec2_public_subnet/README.md
- calculated_policies/aws_guardduty_detector_approved_usage/README.md
- calculated_policies/aws_lambda_in_vpc/README.md
- calculated_policies/aws_lambda_not_approved_cross_account_access/README.md
- calculated_policies/aws_s3_bucket_match_tags_on_bucket_and_cmk/README.md
- calculated_policies/aws_s3_bucket_match_tags_on_bucket_and_cmk/default.tfvars
- calculated_policies/aws_s3_bucket_match_tags_on_bucket_and_cmk/main.tf
- calculated_policies/aws_s3_bucket_match_tags_on_bucket_and_cmk/variables.tf
- calculated_policies/aws_s3_bucket_tagging_template/README.md
- calculated_policies/azure_load_balancer_prohibited_ports/README.md
- calculated_policies/multi_cloud_storage_cost_savings/README.md
- repo-tools/templates/calc-policy/aws_s3_bucket_match_tags_on_bucket_and_cmk/template.yml
> Calculated Policy - AWS > S3 > Bucket - Match tags on Bucket and CMK #210

- calculated_policies/README.md
- calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/README.md
- calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/default.tfvars
- calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/main.tf
- calculated_policies/azure_compute_disk_approved_usage_customer_key_encrypted/variables.tf
- repo-tools/templates/calc-policy/azure_compute_disk_approved_usage_customer_key_encrypted/template.yml
> Calculated Policy - Azure > Compute > Disk approved if using customer key encryption #219

- .vscode/launch.json
- .vscode/settings.json
- api_examples/graphql/clients/python/run_controls/README.md
- api_examples/graphql/clients/python/run_controls/run_controls.py
- api_examples/graphql/clients/python/run_controls_batches/README.md
- api_examples/graphql/clients/python/run_controls_batches/run_controls_batches.py
- api_examples/graphql/clients/python/run_policies/README.md
- api_examples/graphql/clients/python/run_policies/run_policies.py
- api_examples/graphql/clients/python/run_policies_batches/README.md
- api_examples/graphql/clients/python/run_policies_batches/run_policies_batches.py
- repo-tools/package.json
- repo-tools/templates/api-examples/clients/python/run_controls/template.yml
- repo-tools/templates/api-examples/clients/python/run_controls_batches/template.yml
- repo-tools/templates/api-examples/clients/python/run_policies/template.yml
> API Examples - Update documentation generated for Policy Runners #233

- api_examples/graphql/clients/python/README.md
- api_examples/graphql/clients/python/aws_import/README.md
- api_examples/graphql/clients/python/get-notifications-by-class/README.md
- api_examples/graphql/clients/python/get-notifications-by-type/README.md
- api_examples/graphql/clients/python/get-notifications-for-resource/README.md
- api_examples/graphql/clients/python/run_controls/README.md
- api_examples/graphql/clients/python/run_controls_batches/README.md
- api_examples/graphql/clients/python/run_policies/README.md
- api_examples/graphql/clients/python/run_policies_batches/README.md
- repo-tools/gen-doc-api-examples.js
- repo-tools/templates/api-examples/index-python.njk
- repo-tools/templates/api-examples/python.njk
> API Examples - Fix bugs in python index template #237

- api_examples/graphql/clients/python/README.md
- api_examples/graphql/clients/python/aws_import/README.md
- api_examples/graphql/clients/python/get-notifications-by-class/README.md
- api_examples/graphql/clients/python/get-notifications-by-type/README.md
- api_examples/graphql/clients/python/get-notifications-for-resource/README.md
- api_examples/graphql/clients/python/run_controls/README.md
- api_examples/graphql/clients/python/run_controls_batches/README.md
- api_examples/graphql/clients/python/run_policies/README.md
- api_examples/graphql/clients/python/run_policies_batches/README.md
- api_examples/graphql/clients/python/turbot/README.md
- repo-tools/gen-doc-api-examples.js
- repo-tools/templates/api-examples/clients/python/turbot/template.yml
- repo-tools/templates/api-examples/python.njk
> API Examples - Add turbot library to document generator #239

- baselines/gcp/gcp_project_import/main.tf
GCP documentation gave us some trouble.  Wanted to update these to make it more clear on what needs to be done to bring a project into GCP.
closes #245
> Baseline - GCP project, improve documentation for clarity #245

- baselines/gcp/gcp_project_import/main.tf
> Baselines - Fix comments for GCP Project #272

- control_objectives/aws_s3_access_logging/README.md
- control_objectives/aws_s3_access_logging/default.tfvars
- control_objectives/aws_s3_access_logging/main.tf
- control_objectives/aws_s3_access_logging/variables.tf
> Control objective - Enforce S3 Access Logging #273

- baselines/azure/azure_active_directory_import/README.md
- baselines/azure/azure_active_directory_import/default.tfvars
- baselines/azure/azure_active_directory_import/main.tf
- baselines/azure/azure_active_directory_import/variables.tf
- baselines/azure/azure_management_group_import/README.md
- baselines/azure/azure_management_group_import/default.tfvars
- baselines/azure/azure_management_group_import/main.tf
- baselines/azure/azure_management_group_import/variables.tf
- baselines/azure/azure_tenant_import/README.md
- baselines/azure/azure_tenant_import/default.tfvars
- baselines/azure/azure_tenant_import/main.tf
- baselines/azure/azure_tenant_import/variables.tf
> Baselines - Add Azure import terraform script for tenant, management group and active directory. Closes #277

- calculated_policies/README.md
- calculated_policies/aws_s3_bucket_approved_usage_acl_cross_account_access/README.md
- calculated_policies/aws_s3_bucket_approved_usage_acl_cross_account_access/default.tfvars
- calculated_policies/aws_s3_bucket_approved_usage_acl_cross_account_access/main.tf
- calculated_policies/aws_s3_bucket_approved_usage_acl_cross_account_access/variables.tf
- repo-tools/templates/calc-policy/aws_s3_bucket_approved_usage_acl_cross_account_access/template.yml
> Calculated Policy - AWS > S3 > Bucket ACL Cross-Account Access #281

- installation/workspace-template.yml
> Update workspace installation template

- api_examples/graphql/clients/node/get-notifications-by-class/package-lock.json
- api_examples/graphql/clients/node/get-notifications-by-class/package.json
- api_examples/graphql/clients/node/get-notifications-by-type/package.json
- api_examples/graphql/clients/node/get-specific-resource-last-notification/package-lock.json
- api_examples/graphql/clients/node/get-specific-resource-last-notification/package.json
> Fix dependabot alerts for node-fetch #317

- .vscode/launch.json
- api_examples/graphql/clients/python/README.md
- api_examples/graphql/clients/shell/README.md
- api_examples/graphql/clients/shell/run-controls/README.md
- api_examples/graphql/clients/shell/run-controls/run-controls.sh
> Introduce run-controls for bash shell #319

- api_examples/graphql/queries/list-ec2-instances-with-public-ip.graphql
- api_examples/graphql/queries/list-ec2-network-interfaces-with-public-ip.graphql
> API Example - List resources that have a public IP address #287

- baselines/azure/azure-cis-v1-section5.2/README.md
- baselines/azure/azure-cis-v1-section5.2/default.tfvars
- baselines/azure/azure-cis-v1-section5.2/main.tf
- baselines/azure/azure-cis-v1-section5.2/variables.tf
> Baseline - Azure CIS v1 section 5.2 enforcement #279

- trimbot/trimbot_modules/s3_bucket.py
> Tools - TrimBot #335

- .vscode/launch.json
- api_examples/graphql/clients/shell/run-policies/README.md
- api_examples/graphql/clients/shell/run-policies/run-policies.sh
> Shell examples - Run all policies #343

- trimbot/config/aws_account_only.yaml
- trimbot/config/managed_account.yaml
- trimbot/config/master_account.yaml
- trimbot/main.py
- trimbot/trimbot_modules/configuration.py
- trimbot/trimbot_modules/resource_service_factory.py
> TrimBot - Expand functionality to have AWS only #362

- installation/turbot_bastion_host/README.md
- installation/turbot_bastion_host/turbot_bastion_host.yaml
> Installation - Update turbot_bastion_host file to support connections to Redis #396

- baselines/turbot/example_folder_hierarchy/README.md
- baselines/turbot/example_folder_hierarchy/default.tfvars
- baselines/turbot/example_folder_hierarchy/main.tf
- baselines/turbot/example_folder_hierarchy/variables.tf
- calculated_policies/aws_ec2_cross_account_ami_snapshot/README.md
- calculated_policies/aws_ec2_cross_account_ami_snapshot/default.tfvars
- calculated_policies/aws_ec2_cross_account_ami_snapshot/main.tf
- calculated_policies/aws_ec2_cross_account_ami_snapshot/variables.tf
> Calculated Policy - Example folder structure using Terraform #305

- calculated_policies/aws_vpc_security_group_restrict/README.md
> Control Objective - Fix title for AWS EC2 - Restrict Instance images to trusted AWS accounts AMIs #301

- api_examples/graphql/queries/controls-to-investigate.graphql
- api_examples/graphql/queries/install_mod.graphql
- api_examples/graphql/queries/list_aws_accounts.graphql
- api_examples/graphql/queries/list_azure_subscriptions.graphql
- api_examples/graphql/queries/list_controls_by_resource_type.graphql
- api_examples/graphql/queries/list_controls_ten_oldest_alerts_for_s3.graphql
- api_examples/graphql/queries/list_directories.graphql
- api_examples/graphql/queries/list_folders.graphql
- api_examples/graphql/queries/list_installed_mods_by_resource_type.graphql
- api_examples/graphql/queries/list_notifications_for_controls_that_moved_to_alarm_state.graphql
- api_examples/graphql/queries/list_profile.graphql
- api_examples/graphql/queries/list_resources_by_resource_type.graphql
- api_examples/graphql/queries/list_resources_by_resource_type_in_specific_account.graphql
- api_examples/graphql/queries/list_resources_by_resource_type_with_specific_tag.graphql
- api_examples/graphql/queries/list_resources_by_resource_type_with_write_acl.graphql
- api_examples/graphql/queries/list_smart_folder_attachments.graphql
- api_examples/graphql/queries/list_smart_folders.graphql
- api_examples/graphql/queries/reset-password.graphql
- api_examples/graphql/queries/resource_control_policy.graphql
- api_examples/graphql/queries/storage-resources.graphql
- api_examples/graphql/queries/uninstall_mod.graphql
> GraphQl - Updating Existing Graphql Examples in TDK #339

- baselines/getting_started/turbot/cis_mod/README.md
- baselines/getting_started/turbot/cis_mod/mod_install.tf
- baselines/getting_started/turbot/cis_mod/outputs.tf
- baselines/getting_started/turbot/cis_mod/provider.tf
- baselines/getting_started/turbot/cis_mod/variables.tf
> Baseline - Add CIS install mod. Closes #455

- baselines/getting_started/gcp/gcp_mods/README.md
- baselines/getting_started/gcp/gcp_mods/mod_install.tf
- baselines/getting_started/gcp/gcp_mods/ouputs.tf
- baselines/getting_started/gcp/gcp_mods/provider.tf
- baselines/getting_started/gcp/gcp_mods/variables.tf
> Baseline - Add GCP install mods. Closes #454

- calculated_policies/gcp_compute_engine_image_approved_usage/README.md
- calculated_policies/gcp_compute_engine_image_approved_usage/default.tfvars
- calculated_policies/gcp_compute_engine_image_approved_usage/main.tf
- calculated_policies/gcp_compute_engine_image_approved_usage/variables.tf
> Calculated Policy - GCP sets approved images based on project or approved image lists. Closes #417

- calculated_policies/aws_vpc_unallocated_ip_approved_usage/README.md
- calculated_policies/aws_vpc_unallocated_ip_approved_usage/default.tfvars
- calculated_policies/aws_vpc_unallocated_ip_approved_usage/main.tf
- calculated_policies/aws_vpc_unallocated_ip_approved_usage/variables.tf
> Calculated Policy - AWS find unallocated elastic IPs. Closes #418

- baselines/getting_started/aws/aws_check_iam/deny_star_policy_stmt.tf
> Baseline - Fix `AWS > IAM > Policy > Approved > Usage` calc policy logic #461

- api_examples/graphql/queries/password_reset/README.md
> Documentation - Amend password reset readme.md #481

- api_examples/graphql/queries/list_total_resources_by_resource_type.graphql
> GraphQL - List resource types by totals #479

- calculated_policies/aws_ec2_volume_unattached/README.md
- calculated_policies/aws_ec2_volume_unattached/default.tfvars
- calculated_policies/aws_ec2_volume_unattached/main.tf
- calculated_policies/aws_ec2_volume_unattached/variables.tf
> Calculated Policy - EC2 volume unattached #483

- env_health_checks/README.md
- env_health_checks/cloudwatch_insights/view_all_messages_by_aws_account_id.query
- env_health_checks/cloudwatch_insights/view_all_messages_by_raw_event.query
- env_health_checks/cloudwatch_insights/view_all_messages_by_workspace.query
- env_health_checks/cloudwatch_insights/view_all_messages_for_workspace_by_message_type.query
- env_health_checks/cloudwatch_insights/view_all_messages_for_workspace_by_time.query
- env_health_checks/cloudwatch_insights/view_all_messages_tick_turbot_next.query
- env_health_checks/cloudwatch_insights/view_external_messages_by_account_id_by_event_source.query
- env_health_checks/graphql/list_aws_resourcetype_summaries.graphql
- env_health_checks/graphql/list_azure_resourcetype_summaries.graphql
- env_health_checks/graphql/list_controls_summary_by_state.graphql
- env_health_checks/graphql/list_gcp_resourcetype_summaries.graphql
> Environment health checks #489

- installation/security_groups.yml
> Installation - Update sec group rules #487

- baselines/getting_started/turbot/smart_retention/README.md
- baselines/getting_started/turbot/smart_retention/default.tfvars
- baselines/getting_started/turbot/smart_retention/main.tf
- baselines/getting_started/turbot/smart_retention/variables.tf
> Baseline - Smart retention policies #477

- baselines/getting_started/gcp/gcp_check_encryption/bigquery_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/compute_engine_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/dataflow_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/dataproc_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/kubernetes_engine_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/outputs.tf
- baselines/getting_started/gcp/gcp_check_encryption/pub_sub_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/storage_encryption_policies.tf
- baselines/getting_started/gcp/gcp_check_encryption/variables.tf
> Baseline - Simplify GCP check encryption and address consistency #498

- baselines/getting_started/gcp/gcp_check_public_access/compute_engine_policies.tf
- baselines/getting_started/gcp/gcp_check_public_access/network_policies.tf
- baselines/getting_started/gcp/gcp_check_public_access/outputs.tf
- baselines/getting_started/gcp/gcp_check_public_access/trusted_access_policies.tf
- baselines/getting_started/gcp/gcp_check_public_access/variables.tf
> Baseline - Simplify GCP check public access and address consistency #502

- baselines/notifications/security-hub/README.md
> SecHub - Update README #457

- calculated_policies/aws_kms_key_policy_rules/README.md
- calculated_policies/aws_kms_key_policy_rules/kms_rules_policies.tf
- calculated_policies/aws_kms_key_policy_rules/output.tf
- calculated_policies/aws_kms_key_policy_rules/providers.tf
- calculated_policies/aws_kms_key_policy_rules/smart_folder.tf
- calculated_policies/aws_kms_key_policy_rules/variables.tf
> Calculated Policy - KMS Key Rules Approved

- api_examples/graphql/queries/list_current_forecast_spend.graphql
> GraphQL - List Current and Forecast Spend for AWS Accounts

- api_examples/graphql/queries/aws_default_vpc_control_status.graphql
Replaced with working query.
Closes https://github.com/turbotio/ops/issues/94
> Remove old query which did not make sense with the title of the file

- api_examples/graphql/queries/list_aws_region_resources.graphql
> GraphQL - Query to view account resource counts by region #323

- baselines/getting_started/aws/aws_check_stack/aws_account_iam_stack_policies.tf
> Baseline - Update getting started IAM stack baseline setting #518

- baselines/getting_started/aws/aws_baseline/ec2_attribute_policies.tf
> Adding policy to restrict Turbot to only describe DisableApiTermination

- calculated_policies/aws_ami_tag_on_control_alarm/README.md
- calculated_policies/aws_ami_tag_on_control_alarm/ami_policies.tf
- calculated_policies/aws_ami_tag_on_control_alarm/default.tfvars
- calculated_policies/aws_ami_tag_on_control_alarm/output.tf
- calculated_policies/aws_ami_tag_on_control_alarm/providers.tf
- calculated_policies/aws_ami_tag_on_control_alarm/smart_folder.tf
- calculated_policies/aws_ami_tag_on_control_alarm/variables.tf
> Calculated Policy - #tdk-535

- .vscode/launch.json
- api_examples/graphql/clients/shell/run-controls/run-controls.sh
- api_examples/graphql/clients/shell/run-policies/run-policies.sh
> Shell Scripts - Update run-policies and run-controls to be more efficient #546

- calculated_policies/aws_well-architected_security_encryption/README.md
- calculated_policies/aws_well-architected_security_encryption/default.tfvars
- calculated_policies/aws_well-architected_security_encryption/main.tf
- calculated_policies/aws_well-architected_security_encryption/variables.tf
- calculated_policies/aws_well-architected_security_key_management/README.md
- calculated_policies/aws_well-architected_security_key_management/default.tfvars
- calculated_policies/aws_well-architected_security_key_management/main.tf
- calculated_policies/aws_well-architected_security_key_management/variables.tf
Two examples:
- How to query resources in a calc policy.
- How to query control categories in a calc policy.
> Waf calc policy examples

- api_examples/graphql/clients/shell/turbot-aws/README.md
- api_examples/graphql/clients/shell/turbot-aws/turbot-aws.sh
> Shell Scripts - Replacement of Turbot AWS V3 Shell Script #576

- calculated_policies/aws_s3_bucket_tagging_ignore_casing/README.md
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/default.tfvars
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/output.tf
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/policies.tf
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/providers.tf
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/smart_folder.tf
- calculated_policies/aws_s3_bucket_tagging_ignore_casing/variables.tf
> Calculated Policies - Tagging example that ignores casing of key:value pair #580

- workspace_usage/README.md
- workspace_usage/get_workspace_usage.py
- workspace_usage/requirements.txt
- workspace_usage/workspaces.conf
Initial commit of workspace control reporting.
> Workspace Usage Reporting

- migration/steampipe-mod-turbot-migration/README.md
- migration/steampipe-mod-turbot-migration/mod.sp
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users_post.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_roles.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_nonturbot_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_with_inline_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_users_groups.sql
Merged in all of Dave's improvements.
> Migration checks

- migration/steampipe-mod-turbot-migration/mod.sp
Missing comma and duplicate controls have been resolved.
> Mod.sp Fixes

- migration/steampipe-mod-turbot-migration/README.md
- migration/steampipe-mod-turbot-migration/mod.sp
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users_post.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_groups_non_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_roles.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_non_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_nonturbot_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_with_inline_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_users_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_users_two_keys.sql
- Shortening policy_arn to just the policy name itself
- Adding connection_name to each table
- Adding account_id to each table
> Account_id, connection_name and policy_name (instead of full ARN)

- migration/steampipe-mod-turbot-migration/README.md
- migration/steampipe-mod-turbot-migration/mod.sp
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_all_groups_all_users_post.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_groups_non_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_roles.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_policies_attached_users.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_non_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_nonturbot_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_turbot_users_with_inline_policies.sql
- migration/steampipe-mod-turbot-migration/queries/iam_users_groups.sql
- migration/steampipe-mod-turbot-migration/queries/iam_users_two_keys.sql
Get a list of users with two access keys and the IDs for those keys.
> Enumerate access keys

- api_examples/graphql/clients/python/run_controls_batches/requirements.txt
- workspace_usage/requirements.txt
- Update the python package versions to newer values.
- Remove unneeded packages.
> Updated Python Package Versions

- api_examples/graphql/queries/password_reset/README.md
Notes on password complexity and Internal Errors.
> Password Complexity

- api_examples/graphql/clients/python/clean_malformed_akas/README.md
- api_examples/graphql/clients/python/clean_malformed_akas/clean_malformed_akas.py
- api_examples/graphql/clients/python/clean_malformed_akas/requirements.txt
- api_examples/graphql/clients/python/clean_malformed_akas/turbot.py
A single script to destroy then rediscover AWS resources with malformed AKAs (usually missing the partition).
> Clean Malformed AKAs

- cis_enforcements/enforce_aws_cis_v300/enforce_aws_cis_v300_s1_iam/enforce_access_keys.tf
- cis_enforcements/enforce_aws_cis_v300/enforce_aws_cis_v300_s1_iam/enforce_instance_profile.tf
- cis_enforcements/enforce_aws_cis_v300/enforce_aws_cis_v300_s1_iam/enforce_no_admin_access_policies.tf
- cis_enforcements/enforce_aws_cis_v300/enforce_aws_cis_v300_s1_iam/enforce_regional_access_analyzer.tf
- cis_enforcements/enforce_aws_cis_v300/enforce_aws_cis_v300_s1_iam/main.tf
Policy Settings for 
1.16, 1.18, 1.19 and 1.20.
> Cis iam 1.16 22

- runbooks/getting-started/folder hierarchy.md
- Process for creating a folder hierarchy and smart folders.
- Description of Strategic vs Tactical smart folders.
- GraqphQL query to get folder IDs to be used in automated account import.
Creation of the folder hierarchy is a common but underdiscussed process.
> Folder Hierarchy

- hub_content/policy_packs/aws/lambda/enforce_function_to_restrict_public_access/common.tf
- hub_content/policy_packs/aws/lambda/enforce_function_to_restrict_public_access/main.tf
- hub_content/policy_packs/aws/lambda/enforce_function_to_restrict_public_access/policies.tf
> Add policy packs for AWS Lambda

- policy_packs/gcp/cis_v200/section4/README.md
- policy_packs/gcp/cis_v200/section4/main.tf
- policy_packs/gcp/cis_v200/section4/policies.tf
- policy_packs/gcp/cis_v200/section4/providers.tf
> Policy Pack for GCP CIS v2.0 Enforcement for Section 4 - Virtual Machines.

- cis_enforcements/aws/cis_v300_s5_networking/README.md
- policy_packs/gcp/cis_v200/section6/README.md
- policy_packs/gcp/cis_v200/section6/main.tf
- policy_packs/gcp/cis_v200/section6/policies.tf
- policy_packs/gcp/cis_v200/section6/providers.tf
> Policy Pack for GCP CIS v2.0 Enforcement for Section 6 - Cloud SQL Database Services.

- policy_packs/gcp/cis_v200/section1/README.md
- policy_packs/gcp/cis_v200/section1/iam.tf
> Policy Pack for GCP - Add 1.12, 1.13, 1.14, 1.15.

- baselines/getting_started/azure/azure_check_tagging/README.md
Fixed the title to point to Azure, not GCP.
> Update Azure Tags README.md

- .github/workflows/baselines.yml
The GitHub Action automates the application of Terraform configurations in the `baselines/` folder, ensuring that:
- Only the folders with changes are processed.
- Guardrails and mods folders are applied in the correct order.
- Dynamic user profile variables can be passed into the Terraform configuration.
The action is optimized to avoid unnecessary runs, only applying changes in folders that were modified in the current branch relative to `main`.
1. **Detects Changes**: 
- The action runs a `git diff` to detect which folders under the `baselines/` directory have changed, comparing the current branch to the `main` branch (or handling the first commit as a special case). It collects these folders for processing.
2. **Processes Terraform Folders**:
- It has a custom `process_folder` …
> Update Baselines Github Action

- policy_packs/aws/rds/enforce_manual_db_cluster_snapshots_are_shared_with_trusted_accounts/README.md
- policy_packs/aws/rds/enforce_manual_db_cluster_snapshots_are_shared_with_trusted_accounts/main.tf
- policy_packs/aws/rds/enforce_manual_db_cluster_snapshots_are_shared_with_trusted_accounts/policies.tf
- policy_packs/aws/rds/enforce_manual_db_cluster_snapshots_are_shared_with_trusted_accounts/providers.tf
> Add policy pack - AWS > RDS > DB Cluster Snapshot [Manual] > Trusted Access. Closes #863

- policy_packs/aws/rds/enforce_manual_db_instance_snapshots_are_shared_with_trusted_accounts/README.md
- policy_packs/aws/rds/enforce_manual_db_instance_snapshots_are_shared_with_trusted_accounts/main.tf
- policy_packs/aws/rds/enforce_manual_db_instance_snapshots_are_shared_with_trusted_accounts/policies.tf
- policy_packs/aws/rds/enforce_manual_db_instance_snapshots_are_shared_with_trusted_accounts/providers.tf
> Add policy pack - AWS > RDS > DB Snapshot [Manual] > Trusted Access. Closes #861

- policy_packs/aws/redshift/enforce_clusters_are_not_publicly_accessible/README.md
- policy_packs/aws/redshift/enforce_clusters_are_not_publicly_accessible/main.tf
- policy_packs/aws/redshift/enforce_clusters_are_not_publicly_accessible/policies.tf
- policy_packs/aws/redshift/enforce_clusters_are_not_publicly_accessible/providers.tf
> Add policy pack - Redshift Cluster Public Access Check. Closes #859

- guardrails_utilities/python_utils/run_controls_batches/run_controls_batches.py
- guardrails_utilities/python_utils/run_policies_batches/run_policies_batches.py
<details>
<summary>Current Behavior</summary>
```
Testing connection to <workspace> ...
Success! Status Code: 200
Using the filter: policyTypeId:tmod:@turbot/aws-iam#/policy/types/roleActive test sort:timestamp level:self
Looking for targets...
Found 17 Total Targets
{"policyId": "289217560188168", "processId": "339939882807991"}
{"policyId": "289217562416012", "processId": "339939883209401"}
{"policyId": "289217563439457", "processId": "339939883632320"}
{"policyId": "289217573860545", "processId": "339939884037828"}
{"policyId": "289217574326777", "processId": "339939884443336"}
{"policyId": "289217575223738", "processId": "339939884994250"}
{"policyId": "289217577120298", "processId": "339939885553357"}
{"policyId": "289217585168426", "processId": "339939885959887"}
{"policyId": …
```
> Error Handling Enhancement for NoneType in Mutation Responses. Closes #891

- policy_packs/github/enforce_repositories_are_private/README.md
- policy_packs/github/enforce_repositories_are_private/main.tf
- policy_packs/github/enforce_repositories_are_private/policies.tf
- policy_packs/github/enforce_repositories_are_private/providers.tf
> Add policy pack for repository visibility

- policy_packs/github/enforce_discussions_are_enabled_for_repositories/README.md
- policy_packs/github/enforce_discussions_are_enabled_for_repositories/main.tf
- policy_packs/github/enforce_discussions_are_enabled_for_repositories/policies.tf
- policy_packs/github/enforce_discussions_are_enabled_for_repositories/providers.tf
> Add policy pack for Discussions Enabled for Repository

- policy_packs/github/enforce_projects_are_enabled_for_repositories/README.md
- policy_packs/github/enforce_projects_are_enabled_for_repositories/main.tf
- policy_packs/github/enforce_projects_are_enabled_for_repositories/policies.tf
- policy_packs/github/enforce_projects_are_enabled_for_repositories/providers.tf
> Add Policy pack for Projects Enabled for Repositories

- policy_packs/github/enforce_secret_scanning_is_enabled_for_repositories/README.md
- policy_packs/github/enforce_secret_scanning_is_enabled_for_repositories/main.tf
- policy_packs/github/enforce_secret_scanning_is_enabled_for_repositories/policies.tf
- policy_packs/github/enforce_secret_scanning_is_enabled_for_repositories/providers.tf
> Add policy pack for repository secret scanning

- policy_packs/github/enforce_push_protection_is_enabled_for_repositories/README.md
- policy_packs/github/enforce_push_protection_is_enabled_for_repositories/main.tf
- policy_packs/github/enforce_push_protection_is_enabled_for_repositories/policies.tf
- policy_packs/github/enforce_push_protection_is_enabled_for_repositories/providers.tf
> Add policy pack for repository push protection

- policy_packs/github/enforce_forking_is_enabled_for_repositories/README.md
- policy_packs/github/enforce_forking_is_enabled_for_repositories/main.tf
- policy_packs/github/enforce_forking_is_enabled_for_repositories/policies.tf
- policy_packs/github/enforce_forking_is_enabled_for_repositories/providers.tf
> Add policy pack to enable forking for repository

- guardrails_utilities/python_utils/turbot_active_users_permissions/README.md
- guardrails_utilities/python_utils/turbot_active_users_permissions/requirements.txt
- guardrails_utilities/python_utils/turbot_active_users_permissions/sample_turbot_active_users_permissions_20250326.csv
- guardrails_utilities/python_utils/turbot_active_users_permissions/turbot_active_users_permissions.py
Execution:
```
$ python3 turbot_active_users_permissions.py  -p punisher
Script started at 2025-03-26 13:45:05.846028
Testing connection to https://punisher-turbot.acme.com ...
Success! Status Code: 200
Collecting identity permissions data for the last 7 day(s)...
Data successfully written to punisher_turbot_active_users_permissions_20250326.csv
Total identities processed: 3
Total rows written: 6
Script completed at 2025-03-26 13:45:08.280521
Total time taken: 2.43 seconds
Total API calls made: 1
```
> Add Turbot Active Users & Permissions Report
